# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.4
_src_path: https://github.com/jupyterlab/extension-template
author_email: info@khulnasoft.com
author_name: khulnasoft_jupyter
has_binder: true
has_settings: true
kind: server
labextension_name: khulnasoft_jupyter
project_short_description: GitHub Copilot for Jupyter
python_name: khulnasoft_jupyter
repository: ''
test: false

